name: Remote Control Build

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          cache: "pip"

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install -U platformio
          platformio update

      - name: Build bare metal
        run: platformio run

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-firmware  ${{ matrix.os }}
          path: |
            .pio/build/**/*.bin
